# docker-compose.yml
version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: flight_reservation_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flight
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    driver: local